// LIST
export const FETCH_POKEMON_LIST_START = 'FETCH_POKEMON_LIST_START';
export const FETCH_POKEMON_LIST_SUCCESS = 'FETCH_POKEMON_LIST_SUCCESS';
export const FETCH_POKEMON_LIST_ERROR = 'FETCH_POKEMON_LIST_ERROR';

export const FILTER_POKEMON_LIST_START = 'FILTER_POKEMON_LIST_START';
export const FILTER_POKEMON_LIST_SUCCESS = 'FILTER_POKEMON_LIST_SUCCESS';
export const FILTER_POKEMON_LIST_ERROR = 'FILTER_POKEMON_LIST_ERROR';

// SEARCH
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

// THEME
export const CHANGE_THEME = 'CHANGE_THEME';