// LIST
export const FETCH_POKEMON_LIST = 'FETCH_POKEMON_LIST';

// SEARCH
export const SEARCH_FOR_POKEMON = 'SEARCH_FOR_POKEMON';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';